### ISSUE TITLE
python Demo_Transfer_rgb.py 

### ISSUE THREAD

**Issue by panna19951227** [USTC-Video-Understanding/I3D_Finetune#1]
Demo_Transfer_rgb.py [-h] dataset_name data_tag
python Demo_Transfer_rgb.py need two arguments dataset_name data_tag

**Comment by vra** [comment]
Hi @panna19951227 ,
Thanks for your trial, we are working on this to solve the issue you raised.

**Comment by vra** [comment]
Hi @panna19951227 ,
Please retry our code. I guess the mentioned issue has been sovled.

**Comment by panna19951227** [comment]
![default](https://user-images.githubusercontent.com/39176743/40296711-f8f5a074-5d0f-11e8-9e87-4b1201dfe40c.PNG)
I have met this problem,may I ask for your help?

**Comment by vra** [comment]
I guess this issue is about the version of Python. Since our code use Python2.7 and you are using Python3.6, could you please use Python2.7 and try again?
