### ISSUE TITLE
multi GPU

### ISSUE THREAD

**Issue by panna19951227** [USTC-Video-Understanding/I3D_Finetune#11]
if I want to use multi GPUs to train ,what should I do?

**Comment by vra** [comment]
At current our code doesn't support multi GPU training. You can adapt it yourself following TensorFlow multi GPU tutorials.

**Comment by arunponnusamy** [comment]
Hello @panna19951227 , were you able to adapt the code for multi GPU training ? 
It would be great if you can share any updates. Thanks.
