### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ir0nt0ad** [USTC-Video-Understanding/I3D_Finetune#28]
i3d.py is licensed under Apache License 2.0 - is the rest of the code in this repository being released under the same license as well? Many thanks!

**Comment by ir0nt0ad** [comment]
@Rhythmblue @AlexHu123

**Comment by Rhythmblue** [comment]
We will follow the original license in official i3d code.

**Comment by ir0nt0ad** [comment]
Thanks @Rhythmblue!
